#!/bin/bash
PS3='Please enter your choice: '
Option1="Compile CM9"
Option2="Compile AOKP"
Option3="Compile CornerStone"
options=("$Option1" "$Option2" "$Option3" "Quit")

select opt in "${options[@]}"
do
    case $opt in
        "$Option1")
            cd builds/cm7/vendor/hillbillyhacker
            clear
            ./build-cm9
            break
            ;;
        "$Option2")
            cd builds/aokp/vendor/hillbillyhacker
            clear
            ./build-aokp
            break
            ;;
        "$Option3")
            cd builds/cornerstone/vendor/hillbillyhacker
            clear
            ./build-cs9
            break
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done
