#!/bin/bash
PS3='Please enter your choice: '
Option1="Compile CM7"
Option2="Compile CM9"
options=("$Option1" "$Option2" "Quit")

select opt in "${options[@]}"
do
    case $opt in
        "$Option1")
            cd builds/cm7/vendor/hillbillyhacker
            clear
            ./build-cm7
            break
            ;;
        "$Option2")
            cd builds/cm9/vendor/hillbillyhacker
            clear
            ./build-cm9
            break
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done
